language: node_js
node_js:
  - 8
notifications:
  email: false
deploy:
  provider: heroku
  app: pseudoname-api
  api_key:
    secure: M68StHG4SSj9glCIQzXimgWDpEmWnYsEqH4YqtYXBJufxgHpR53yh96x9vGJSsQt1/WmOkh0yWokRh2Fk0QszxhKlNEk7/3B57pJTZ/FHDzsY9WqdfT4NNw9qovSIO65TK/YYkaWTeDyIQiJ0DUB6jew2VMpK7m9XARoGKAZoxDjIaXebIK7DDLwRSAA021RmzTKEc+TYzv13qh3p4X5GMDItUSQlRwV2K9hfHbUNMM1OatBhOzABxj1PS95CBf38X2dScca5GJaus5Z65klXA5J1y6Jc8dGT4wQI4culRZ8IM12otPXYc6c53BOXi8YctHXda+SnkW2hi77VizRtaLOI6JnDRxnKcCvllIQ2QDWgbnPv9booC4LpQdjlZrCZTPYodpK48bBVq0ZzHHlSfmQ3mK0zNH+SUeLOKUq9HhgMJLbZLSf+S6qJpvJPufurSIDw01sVBu/VSuo/KtNKBvJBC2ovWwxDIKXNwFDhMH3RbkPdD+JfioI9UJjzK0NZMNoAxr+VTxbRbgGwdCMTJA7B88tyJvmgljxhgfpu9A8dR3MhKFToE69cj/T6zYzYzqTI2GcC2FVSD+PJmJYk0qvHgLSuYvfvgQ17Zr+g7FykXaIXecqCkYceclYFePgAdeSeytb4ztGq3VOB7hq9J204wEY31N6FMyaC2UzW0k=
